update makefile,setup.sh and dockerfile

diff --git a/module4_task1/build/Dockerfile b/module4_task1/build/Dockerfile
--- a/module4_task1/build/Dockerfile
+++ b/module4_task1/build/Dockerfile
@@ -1,5 +1,5 @@
 FROM golang:1.15.8-buster
-WORKDIR /module4_task0
+WORKDIR /module4_task1
 COPY . .
 RUN apt-get update
 ENV NODE_VERSION=16.13.0
@@ -13,8 +13,11 @@ ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
 RUN node --version
 RUN npm --version
 RUN curl -L https://github.com/gohugoio/hugo/releases/download/v0.109.0/hugo_extended_0.109.0_linux-amd64.deb -o hugo.deb
-RUN apt install ./hugo.deb
+RUN test -e /tmp/hugo.deb && dpkg -i /tmp/hugo.deb || echo 'File not found'
 RUN npm install -g markdownlint-cli
 RUN apt-get update -y && apt-get install -y docker.io
-RUN make build
+RUN apt-get install -y python3-pip
+RUN pip3 install awscli
+RUN apt-get install -y jq
 RUN make package
+RUN make build
